# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParaHuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cape_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'ParaHuman',
                'verbose_name_plural': 'ParaHumans',
            },
        ),
        migrations.AddField(
            model_name='entrance',
            name='parahumans',
            field=models.ManyToManyField(related_name='entrances', to='wiki.ParaHuman'),
        ),
    ]
